#ifndef PDENGINE_BUILD_OPTIONS_H_
#define PDENGINE_BUILD_OPTIONS_H_
#pragma once

#define PDE_BUILDOPT_CONFIG_DIR "@PDE_CONFIG_DIR@"
#define PDE_BUILDOPT_CONFIG_FILENAME "@PDE_CONFIG_FILENAME@"
#define PDE_BUILDOPT_DATA_DIR "@PDE_DATA_DIR@"
#define PDE_BUILDOPT_BUILD_TYPE "@CMAKE_BUILD_TYPE@"
#define PDE_BUILDOPT_ENGINE_NAME "@PROJECT_NAME@"
#define PDE_BUILDOPT_ENGINE_VERSION "@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"

#endif /* PDENGINE_BUILD_OPTIONS_H_ */
